name: Run Python Tests

on:
  push:
    branches: [ "main "]
  pull_request:
    branches: [ "main" ]


jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.5

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests wits Allure
        run: |
          pytest --alluredir=allure-results

      - name: Generate Allure Report
        uses: simple-elf/allure-report-actions@v1.7
        if: always()
        with:
          allure_results: allure-results
          allure_report: allure-report
