name: Run Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Run tests
      run: |
        pytest --browser=chrome --alluredir=allure-results

    - name: Generate Allure Report
      if: always()
      uses: simple-elf/allure-report-actions@v1.7
      with:
        allure_results: allure-results
        allure_report: allure-report

    - name: Upload Allure Report as Artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report